import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className="pd-4">
        {/* Logo in top-right */}
        <div className="fixed top-4 right-4 z-50">
          <img src="/logo_u.png" alt="VirtualSikkim Logo" className="w-20 h-auto" />
        </div>

        {/* Page content */}
        {children}
      </body>
    </html>
  );
}
